// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9FQtBrQQIov6r2avlfXJrVXftSQZ_bhE',
    appId: '1:889220564921:web:e8270d6864b1d403e8d868',
    messagingSenderId: '889220564921',
    projectId: 'todo-share-f61e2',
    authDomain: 'todo-share-f61e2.firebaseapp.com',
    storageBucket: 'todo-share-f61e2.appspot.com',
    measurementId: 'G-RYQ3MQTQCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUu0wyUyLLDy4wIaj4x6dkLHHidWoLwc',
    appId: '1:889220564921:android:5f7e02c1b08f2d94e8d868',
    messagingSenderId: '889220564921',
    projectId: 'todo-share-f61e2',
    storageBucket: 'todo-share-f61e2.appspot.com',
  );
}
